name: floor_ffi
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.2.0
homepage: https://floor.codes
publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  floor_annotation:
    git:
      url: https://github.com/user9481291243/floor.git
      ref: develop
      path: floor_annotation   
  floor_common:
    git:
      url: https://github.com/user9481291243/floor.git
      ref: develop
      path: floor_common   
  meta:
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.2+1
